services:
  postgres:
    image: postgres:13
    container_name: biblioteca_postgres
    environment:
      POSTGRES_USER: BIBLIOTECA
      POSTGRES_PASSWORD: biblioteca33!
      POSTGRES_DB: biblioteca_virtual_33_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:s